package com.ucgi.integrationapi.user;

import com.ucgi.integrationapi.error.ResourceNotFoundException;
import java.text.Normalizer;
import java.time.Instant;
import java.util.List;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

/**
 * Administración de usuarios del CRM. Para los campos no mapeados todavía en
 * la entity {@link User} (email, active, createdAt) se usa {@link JdbcTemplate}
 * directo — evita ampliar la entidad solo para esta HU.
 *
 * <p>Cuando se crea un usuario sin password, se genera automáticamente como
 * {@code nombre.apellido} (sin tildes, lowercase) y se marca
 * {@code must_change_password = true} para que el usuario la cambie en su
 * primer login. La contraseña en claro se devuelve UNA SOLA VEZ al admin que
 * provisionó el usuario — coherente con el modelo "midPoint provisiona +
 * agente cambia password" que pidió el profe.
 */
@Service
public class UserService {

    private final UserRepository repository;
    private final PasswordEncoder encoder;
    private final JdbcTemplate jdbc;

    public UserService(UserRepository repository,
                       PasswordEncoder encoder,
                       JdbcTemplate jdbc) {
        this.repository = repository;
        this.encoder = encoder;
        this.jdbc = jdbc;
    }

    @Transactional(readOnly = true)
    public List<UserController.UserResponse> list() {
        return jdbc.query(
                "SELECT id, username, email, full_name, role, active, created_at "
                        + "FROM users ORDER BY username",
                (rs, i) -> new UserController.UserResponse(
                        rs.getLong("id"),
                        rs.getString("username"),
                        rs.getString("email"),
                        rs.getString("full_name"),
                        rs.getString("role"),
                        rs.getBoolean("active"),
                        rs.getTimestamp("created_at").toInstant(),
                        null));
    }

    @Transactional
    public UserController.UserResponse create(UserController.UserCreateRequest req) {
        String initialPassword = req.password() != null && !req.password().isBlank()
                ? req.password()
                : derivePasswordFromName(req.fullName(), req.username());
        boolean autoGenerated = req.password() == null || req.password().isBlank();
        String hash = encoder.encode(initialPassword);
        try {
            jdbc.update("INSERT INTO users (username, email, full_name, password_hash, role, active, must_change_password) "
                            + "VALUES (?, ?, ?, ?, ?, ?, ?)",
                    req.username(), req.email(), req.fullName(), hash, req.role(), true, autoGenerated);
        } catch (DataIntegrityViolationException e) {
            throw new ResponseStatusException(
                    org.springframework.http.HttpStatus.CONFLICT,
                    "Username o email ya en uso");
        }
        Long id = jdbc.queryForObject(
                "SELECT id FROM users WHERE username = ?", Long.class, req.username());
        UserController.UserResponse base = findResponse(id);
        // Devolvemos la password en claro UNA VEZ cuando fue autogenerada.
        return autoGenerated
                ? new UserController.UserResponse(base.id(), base.username(), base.email(),
                        base.fullName(), base.role(), base.active(), base.createdAt(), initialPassword)
                : base;
    }

    @Transactional
    public UserController.UserResponse updateRole(Long id, String role) {
        int rows = jdbc.update("UPDATE users SET role = ? WHERE id = ?", role, id);
        if (rows == 0) {
            throw new ResourceNotFoundException("Usuario no encontrado: " + id);
        }
        return findResponse(id);
    }

    @Transactional
    public void delete(Long id) {
        if (!repository.existsById(id)) {
            throw new ResourceNotFoundException("Usuario no encontrado: " + id);
        }
        repository.deleteById(id);
    }

    @Transactional
    public void changeOwnPassword(String username, String currentPassword, String newPassword) {
        User user = repository.findByUsername(username)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "Usuario no encontrado: " + username));
        if (user.getPasswordHash() == null
                || !encoder.matches(currentPassword, user.getPasswordHash())) {
            throw new ResponseStatusException(
                    org.springframework.http.HttpStatus.UNAUTHORIZED,
                    "La contraseña actual no es correcta");
        }
        if (newPassword == null || newPassword.length() < 8) {
            throw new ResponseStatusException(
                    org.springframework.http.HttpStatus.BAD_REQUEST,
                    "La nueva contraseña debe tener al menos 8 caracteres");
        }
        user.setPasswordHash(encoder.encode(newPassword), false);
        repository.save(user);
    }

    private UserController.UserResponse findResponse(Long id) {
        return jdbc.queryForObject(
                "SELECT id, username, email, full_name, role, active, created_at "
                        + "FROM users WHERE id = ?",
                (rs, i) -> new UserController.UserResponse(
                        rs.getLong("id"),
                        rs.getString("username"),
                        rs.getString("email"),
                        rs.getString("full_name"),
                        rs.getString("role"),
                        rs.getBoolean("active"),
                        rs.getTimestamp("created_at").toInstant(),
                        null),
                id);
    }

    /**
     * Convierte "Juan Pérez Rodríguez" en "juan.perez" — patrón que el profe
     * mencionó en clase y que muchos call centers usan como password inicial.
     * Si por algún motivo no se puede derivar (un solo token), cae al username.
     */
    static String derivePasswordFromName(String fullName, String fallbackUsername) {
        if (fullName == null) return fallbackUsername;
        String normalized = Normalizer.normalize(fullName, Normalizer.Form.NFD)
                .replaceAll("\\p{InCombiningDiacriticalMarks}+", "")
                .toLowerCase();
        String[] tokens = normalized.split("\\s+");
        if (tokens.length == 0 || tokens[0].isBlank()) return fallbackUsername;
        String first = tokens[0];
        String last = tokens.length >= 2 ? tokens[1] : tokens[0];
        return (first + "." + last).replaceAll("[^a-z0-9.]", "");
    }

    @SuppressWarnings("unused")
    private Instant nowMarker() {
        return Instant.now();
    }
}
