/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        display: ["Space Grotesk", "system-ui", "sans-serif"],
        body: ["Hanken Grotesk", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      colors: {
        // shadcn aliases
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        // DialFlow custom palette
        df: {
          bg: "hsl(var(--df-bg))",
          surface: "hsl(var(--df-surface))",
          "surface-2": "hsl(var(--df-surface-2))",
          "surface-3": "hsl(var(--df-surface-3))",
          border: "hsl(var(--df-border))",
          "border-strong": "hsl(var(--df-border-strong))",
          text: "hsl(var(--df-text))",
          "text-muted": "hsl(var(--df-text-muted))",
          "text-dim": "hsl(var(--df-text-dim))",
          navy: "hsl(var(--df-navy))",
          "navy-soft": "hsl(var(--df-navy-soft))",
          "rail-text": "hsl(var(--df-rail-text))",
          brand: "hsl(var(--df-brand))",
          "brand-bright": "hsl(var(--df-brand-bright))",
          "brand-ink": "hsl(var(--df-brand-ink))",
          "brand-soft": "hsl(var(--df-brand-soft))",
          call: "hsl(var(--df-call))",
          "call-soft": "hsl(var(--df-call-soft))",
          hang: "hsl(var(--df-hang))",
          "hang-soft": "hsl(var(--df-hang-soft))",
          "st-available": "hsl(var(--df-st-available))",
          "st-break": "hsl(var(--df-st-break))",
          "st-busy": "hsl(var(--df-st-busy))",
          "st-dnd": "hsl(var(--df-st-dnd))",
          "st-offline": "hsl(var(--df-st-offline))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      animation: {
        "df-pulse": "df-pulse 1.6s infinite",
        "df-ring": "df-ring 1.3s infinite",
        "df-fade": "df-fade .2s ease-out",
        "df-in": "df-in .16s ease-out",
        "df-slidein": "df-slidein .2s ease-out",
        "df-pop": "df-pop .2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
